use_frameworks!

target 'RxASDiff_Example' do
  pod 'RxASDiff', :path => '../'

  target 'RxASDiff_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'RxTest'
  end
end
