language: objective-c
osx_image: xcode9.3

cache: cocoapods
podfile: Example/Podfile

before_install:
  - pod install --repo-update --project-directory=Example
  
branches:
  only:
    - master
    
script:
- xcodebuild clean -workspace Example/RxASDiff.xcworkspace -scheme RxASDiff | xcpretty
- xcodebuild build -sdk iphonesimulator -workspace Example/RxASDiff.xcworkspace -scheme RxASDiff CODE_SIGNING_REQUIRED=NO | xcpretty